# ---------------------------------------------------------------------------
# theTrafficScript.py
# Created on: Tue Mar 08 2011 09:59:05 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcpy, time

# Create the Geoprocessor object
#gp.SetProduct("ArcInfo")
arcpy.OverWriteOutput = True

# Load required toolboxes...
#gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")
#gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")

#Variables
GRID_CONDITIONING_GIS_sde = "Database Connections\\GRID_CONDITIONING.GIS.sde"
InClassPath = "Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS." + sys.argv[1]
theOutput = "Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS." + sys.argv[2]
theUpdatedOutput = "Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS.X_" + sys.argv[2]

time.sleep(60)
arcpy.Update_analysis(theOutput, InClassPath, theUpdatedOutput,"BORDERS", "1 Feet")
arcpy.Delete_management(theOutput, "")
arcpy.Rename_management(theUpdatedOutput, sys.argv[2], "")
