# ---------------------------------------------------------------------------
# UpdateCellCounts.py
# Created on: Tue Feb 15 2011 08:32:55 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------
#this code is perfect for updating the percent overlap, but not so great for
#updating the land use types of the data.  This could be used as the input
#method for creating the land use tables:  The cut up areas could be counted
#and applied to the grid layer one at a time.
# Import system modules
import sys, string, os, arcpy, pyodbc as p#arcgisscripting
from arcpy import env

arcpy.OverWriteOutput = True
arcpy.env.workspace = "Database Connections\\GRID_CONDITIONING.GIS.sde"# (VERSION:DBO.DEFAULT)"
Password = sys.argv[1]

#============================
#Connect to the server
#============================
server = 'BESDBDEV1'
database = 'GRID_CONDITIONING'
connStr = (r'DRIVER={SQL Server}; SERVER=' + server + ';DATABASE=' + database + ';' + 'UID=GIS;PWD=' + Password)
conn = p.connect(connStr)

#============================
#Prepare SQL Query
#============================
theSQL =            "DELETE "
theSQL = theSQL +   "FROM   GRID_BMP_Transfer "

#============================
#Execute the query
#============================
dbCursor = conn.cursor()
dbCursor.execute(theSQL)
conn.commit()

#===========================================
fcList = arcpy.ListFeatureClasses()
for fc in fcList:

    if fc.split('.')[2][0] == "Y":
        OTableName = fc.split('.')[2]
        ColumnName = OTableName[1:]

        #============================
        #Prepare SQL Query
        #============================
        theSQL =            "INSERT "
        theSQL = theSQL +   "INTO   GRID_BMP_Transfer "
        theSQL = theSQL +   "       ("
        theSQL = theSQL +   "           DESCRIPTION,"
        theSQL = theSQL +   "           [Percent_Overlap],"
        theSQL = theSQL +   "           BMP_TYPE,"
        theSQL = theSQL +   "           Description_2"
        theSQL = theSQL +   "       ) "
        
        
        theSQL = theSQL +   "SELECT "
        theSQL = theSQL +   "SourceObjectID,  theFrac, area_, area_ "
        theSQL = theSQL +   "FROM   " + OTableName + " "
        print theSQL
        #============================
        #Execute the query
        #============================
        dbCursor = conn.cursor()
        dbCursor.execute(theSQL)
        conn.commit()
