# ---------------------------------------------------------------------------
# UpdateCellCounts.py
# Created on: Tue Feb 15 2011 08:32:55 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------
#this code is perfect for updating the percent overlap, but not so great for
#updating the land use types of the data.  This could be used as the input
#method for creating the land use tables:  The cut up areas could be counted
#and applied to the grid layer one at a time.
# Import system modules
import sys, string, os, arcpy, pyodbc as p#arcgisscripting
from arcpy import env

CellSize = sys.argv[1]
Password = sys.argv[2]
arcpy.OverWriteOutput = True
arcpy.env.workspace = "Database Connections\\GRID_CONDITIONING.GIS.sde"# (VERSION:DBO.DEFAULT)"

#============================
#Connect to the server
#============================
server = 'BESDBDEV1'
database = 'GRID_CONDITIONING'
connStr = (r'DRIVER={SQL Server}; SERVER=' + server + ';DATABASE=' + database + ';' + 'UID=GIS;PWD=' + Password)
conn = p.connect(connStr)

#===========================================
fcList = arcpy.ListFeatureClasses()
for fc in fcList:
    if fc.split('.')[2] == "OIMP":
        OTableName = fc.split('.')[2]
        #============================
        #Prepare SQL Query
        #============================
        theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
        theSQL = theSQL +   "SET    ROW_CellCount = " + OTableName + ".theFrac*4*" + OTableName + ".Area_ft2*100.000/("+CellSize+"*"+CellSize+".000), "
        theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = " + OTableName + ".Area_ft2 "
        theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
        theSQL = theSQL +   "       INNER JOIN " 
        theSQL = theSQL +   "       " + OTableName + " "
        theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = " + OTableName + ".SourceObjectID"
        print theSQL
        #============================
        #Execute the query
        #============================
        dbCursor = conn.cursor()
        dbCursor.execute(theSQL)
        conn.commit()
    else :
        thisVariable = 1
        #OTableName = fc.split('.')[2]
        #ColumnName = OTableName[1:]

        #============================
        #Prepare SQL Query
        #============================
        #theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
        #theSQL = theSQL +   "SET    " + ColumnName + "_LUCellCount = " + OTableName + ".theFrac*4*" + OTableName + ".Area_ft2*100.000/("+CellSize+"*"+CellSize+".000), "
        #theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = " + OTableName + ".Area_ft2 "
        #theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
        #theSQL = theSQL +   "       INNER JOIN " 
        #theSQL = theSQL +   "       " + OTableName + " "
        #theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = " + OTableName + ".SourceObjectID"
        #print theSQL
        #============================
        #Execute the query
        #============================
        #dbCursor = conn.cursor()
        #dbCursor.execute(theSQL)
        #conn.commit()

#============================
#Prepare SQL Query
#============================
#theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "SET    MFR_LUCellCount = O3.theFrac*4*O3.Area_ft2/100.00, "
#theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = O3.Area_ft2 "
#theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "       INNER JOIN " 
#theSQL = theSQL +   "       O3 "
#theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = O3.SourceObjectID"

#============================
#Execute the query
#============================
#dbCursor = conn.cursor()
#dbCursor.execute(theSQL)
#conn.commit()

#============================
#Prepare SQL Query
#============================
#theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "SET    POS_LUCellCount = O4.theFrac*4*O4.Area_ft2/100.00, "
#theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = O4.Area_ft2 "
#theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "       INNER JOIN " 
#theSQL = theSQL +   "       O4 "
#theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = O4.SourceObjectID"

#============================
#Execute the query
#============================
#dbCursor = conn.cursor()
#dbCursor.execute(theSQL)
#conn.commit()

#============================
#Prepare SQL Query
#============================
#theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "SET    TRA_LUCellCount = O5.theFrac*4*O5.Area_ft2/100.00, "
#theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = O5.Area_ft2 "
#theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "       INNER JOIN " 
#theSQL = theSQL +   "       O5 "
#theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = O5.SourceObjectID"

#============================
#Execute the query
#============================
#dbCursor = conn.cursor()
#dbCursor.execute(theSQL)
#conn.commit()

#============================
#Prepare SQL Query
#============================
#theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "SET    SFR_LUCellCount = O6.theFrac*4*O6.Area_ft2/100.00, "
#theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = O6.Area_ft2 "
#theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "       INNER JOIN " 
#theSQL = theSQL +   "       O6 "
#theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = O6.SourceObjectID"

#============================
#Execute the query
#============================
#dbCursor = conn.cursor()
#dbCursor.execute(theSQL)
#conn.commit()

#============================
#Prepare SQL Query
#============================
#theSQL =            "UPDATE GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "SET    VAC_LUCellCount = O7.theFrac*4*O7.Area_ft2/100.00, "
#theSQL = theSQL +   "       GRID_WshdGrd100FtOpt.Area_ft2 = O7.Area_ft2 "
#theSQL = theSQL +   "FROM   GRID_WshdGrd100FtOpt "
#theSQL = theSQL +   "       INNER JOIN " 
#theSQL = theSQL +   "       O7 "
#theSQL = theSQL +   "       ON  GRID_WshdGrd100FtOpt.Description = O7.SourceObjectID"

#============================
#Execute the query
#============================
#dbCursor = conn.cursor()
#dbCursor.execute(theSQL)
#conn.commit()



