# ---------------------------------------------------------------------------
# theTrafficScript.py
# Created on: Tue Mar 08 2011 09:59:05 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcpy, time
from arcpy import env
# Create the Geoprocessor object
#gp.SetProduct("ArcInfo")
arcpy.OverWriteOutput = True

# Load required toolboxes...
GRID_CONDITIONING_GIS_sde = "Database Connections\\GRID_CONDITIONING.GIS.sde"
InClassPath = sys.argv[1]#"Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS." + 

time.sleep(6)
try:
    arcpy.Delete_management("Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS."+sys.argv[2], "")
except:
    print("")

arcpy.FeatureClassToFeatureClass_conversion(InClassPath, GRID_CONDITIONING_GIS_sde, sys.argv[2])
