# ---------------------------------------------------------------------------
# CreateGrid.py
# Created on: 2011-08-24 14:59:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, time, sys
# Local variables:
print ("In CreateGrid.py")
time.sleep(1)

theExtentsLayer = sys.argv[1]
cellSize = sys.argv[2]

print ("In CreateGrid.py")
time.sleep(1)

GRID_CONDITIONING_GIS_BasicGrid = "Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS.BasicGrid"

desc = arcpy.Describe(theExtentsLayer)

XMin = desc.extent.XMin - int(cellSize)*2
YMin = desc.extent.YMin - int(cellSize)*2
XMax = desc.extent.XMax + int(cellSize)*2
YMax = desc.extent.YMax + int(cellSize)*2


extentsMin = str(XMin) + " " + str(YMin)
extentsMax = str(XMax) + " " + str(YMax)
extentsYAxis = str(XMin) + " " + str(YMin + 10)

# Process: Create Fishnet
try:
        arcpy.Delete_management(GRID_CONDITIONING_GIS_BasicGrid, "")
except:
        print("Nothing To Delete!")

try:
        arcpy.CreateFishnet_management(GRID_CONDITIONING_GIS_BasicGrid,
                               extentsMin,
                               extentsYAxis,
                               str(cellSize), str(cellSize), "0", "0",
                               extentsMax,
                               "NO_LABELS",
                               "#",
                               "POLYGON")
except:
        print("Could not make fishnet")
# Process: Clip Fishnet
try:
        arcpy.Delete_management(GRID_CONDITIONING_GIS_BasicGrid + "_Clip", "")
        sleep(6)
except :
        print "Could not delete clip"

try:
        arcpy.Clip_analysis(GRID_CONDITIONING_GIS_BasicGrid, theExtentsLayer, GRID_CONDITIONING_GIS_BasicGrid + "_Clip", "0.1 Feet")
except:
        print "Created BasicGrid_Clip"

time.sleep(1)

