# ---------------------------------------------------------------------------
# theTrafficScript.py
# Created on: Tue Mar 08 2011 09:59:05 AM
#   (generated by ArcGIS/ModelBuilder)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcpy, time
from arcpy import env
# Create the Geoprocessor object
#gp.SetProduct("ArcInfo")
arcpy.OverWriteOutput = True

# Load required toolboxes...
#arcpy.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Conversion Tools.tbx")

time.sleep(60)
InClassPath = "Database Connections\\GRID_CONDITIONING.GIS.sde\\GRID_CONDITIONING.GIS." + sys.argv[1]

arcpy.Delete_management(InClassPath, "")
        